### ISSUE TITLE
没成功， 直接返回undefined 

### ISSUE THREAD

**Issue by LixHu** [dongwei1125/juejin-helper#16]
![image](https://github.com/user-attachments/assets/1494d2ce-d9f7-4362-86e9-4ae5ad3a1e88)

**Comment by w157020087** [comment]
掘金把接口改了，第一个签到接口改了 第二个查询抽奖免费次数请求加上了鉴权

**Comment by dongwei1125** [comment]
我排查下，晚上修复一版。

**Comment by dongwei1125** [comment]
掘金新增了反爬虫策略，暂时搁置一段时间，源代码得分析一段时间了，各位同学暂时先手动签到吧。
