### ISSUE TITLE
第一次启动当前矿石数目 0 是什么情况呢？

### ISSUE THREAD

**Issue by zhanzengyu** [dongwei1125/juejin-helper#4]
其他的都正确，就是矿石数目不对
<img width="446" alt="image" src="https://user-images.githubusercontent.com/17486963/196698127-35923aee-806d-4a10-94bc-528fcc176f6a.png">

**Comment by dongwei1125** [comment]
在未签到情况下才会获取矿石总数，你今日已经签到过了，所以总数为0，影响不大，第二次就正常了。
