### ISSUE TITLE
一直提示cookie错误

### ISSUE THREAD

**Issue by jiawenhui593497** [dongwei1125/juejin-helper#8]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/22763277/221793945-5c4324d9-39fd-41a7-886d-789e129e785c.png">

**Comment by dongwei1125** [comment]
检查下你的 `COOKIE` 环境机密是否按 [指南](https://juejin.cn/post/7108615649777156104#heading-9) 配置。
